version: "3.8"
services:

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./db/mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      my_net:
        ipv4_address: 192.168.0.10
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      my_net:
        ipv4_address: 192.168.0.11
    ports:
      - 8081:8081

  postgres:
    image: postgres
    restart: always
    volumes:
      - ./db/postgres:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/
    networks:
      my_net:
        ipv4_address: 192.168.0.20
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    networks:
      my_net:
        ipv4_address: 192.168.0.21
    ports:
      - 8080:8080

  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    networks:
      my_net:
        ipv4_address: 192.168.0.22
    ports:
      - 15432:80

  python:
    container_name: python_env
    build:
      context: docker
      dockerfile: python.dockerfile
    volumes:
      - ./:/app
    networks:
      my_net:
        ipv4_address: 192.168.0.90
    ports:
      - 8000:8000
    user: "${UID}:${GID}"
    working_dir: /app
    stdin_open: true
    tty: true
    command: python3 ./main.py

networks:
  my_net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24