networks:
  my_net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      my_net:
        ipv4_address: 192.168.0.10


  python:
    image: python:3.8
    volumes:
      - ./:/app
    working_dir: /app
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    networks:
      my_net:
        ipv4_address: 192.168.0.20