networks:
  my_net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      my_net:
        ipv4_address: 192.168.0.10

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      my_net:
        ipv4_address: 192.168.0.20
  
  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 15432:80
    environment:
      PGADMIN_DEFAULT_EMAIL: italo@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    networks:
      my_net:
        ipv4_address: 192.168.0.30

  python:
    image: python:3.8
    volumes:
      - ./:/app
    working_dir: /app
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    networks:
      my_net:
        ipv4_address: 192.168.0.60